Repository thedavidang/CSC4151, pull requests merged in 2020-05, with the labels that each got.

#9 Tab 3 Formatting, Sorting, and Filtering Bugfixes [SPEN-30]
  Development/app/src/main/assets/WalletWatch.xml
  Development/app/src/main/java/com/team4/walletwatch/DataManager.kt
  Development/app/src/main/java/com/team4/walletwatch/Entry.kt
  Development/app/src/main/java/com/team4/walletwatch/Main/MainActivity.kt
  Development/app/src/main/java/com/team4/walletwatch/Main/RecyclerAdapter.kt
  Development/app/src/main/java/com/team4/walletwatch/Main/Tab1Fragment.kt
  Development/app/src/main/java/com/team4/walletwatch/Main/Tab3Fragment.kt
  Development/app/src/main/res/layout/layout_card.xml
Labels: bug

#10 Fixed Numpad Bug [SPEN-56]
  Development/app/src/main/java/com/team4/walletwatch/Main/MainActivity.kt
  Development/app/src/main/java/com/team4/walletwatch/Main/Tab1Fragment.kt
Labels: bug

#11 Added Commas to Totals [SPEN-55]
  Development/app/src/main/java/com/team4/walletwatch/Main/Tab2Fragment.kt
Labels: enhancement

#13 Auto-update tab 2
  Development/app/src/main/java/com/team4/walletwatch/Main/Tab2Fragment.kt
Labels: enhancement

#12 Implemented Back-End Category Changing [SPEN-38]
  Development/.idea/caches/build_file_checksums.ser
  Development/app/src/main/AndroidManifest.xml
  Development/app/src/main/assets/Archive.xml
  Development/app/src/main/java/com/team4/walletwatch/DataManager.kt
  Development/app/src/main/java/com/team4/walletwatch/Main/Tab3Fragment.kt
  Development/app/src/main/java/com/team4/walletwatch/Settings/AboutFragment.kt
  Development/app/src/main/java/com/team4/walletwatch/Settings/CategoryFragment.kt
  Development/app/src/main/java/com/team4/walletwatch/Settings/PINFragment.kt
  Development/app/src/main/java/com/team4/walletwatch/SharedViewModel.kt
  Development/app/src/main/res/values/strings.xml
Labels: enhancement

#16 Implemented Category Restoration [SPEN-38]
  Development/app/src/main/java/com/team4/walletwatch/DataManager.kt
  Development/app/src/main/java/com/team4/walletwatch/Entry.kt
Labels: enhancement

#19 Close Keyboard if User Taps Outside [SPEN-56]
  Development/app/src/main/java/com/team4/walletwatch/Main/Tab1Fragment.kt
  Development/app/src/main/java/com/team4/walletwatch/Settings/CategoryFragment.kt
Labels: bug

#20 Added deleteEmptyTags Function [SPEN-56]
  Development/app/src/main/java/com/team4/walletwatch/DataManager.kt
  Development/app/src/main/java/com/team4/walletwatch/Entry.kt
Labels: enhancement

#18 Modified MIT License [SPEN-65]
  Development/app/src/main/res/layout/fragment_terms.xml
  Development/app/src/main/res/values/strings.xml
  LICENSE
Labels: documentation

#22 Optimized and Commented Code [SPEN-55]
  Development/app/src/main/java/com/team4/walletwatch/Main/Tab1Fragment.kt
  Development/app/src/main/java/com/team4/walletwatch/Main/Tab2Fragment.kt
  Development/app/src/main/java/com/team4/walletwatch/Main/Tab3Fragment.kt
  Development/app/src/main/res/layout/fragment_tab2.xml
  Development/app/src/main/res/values/strings.xml
Labels: enhancement

#23 Added About Page [SPEN-47] [SPEN-13]
  Development/app/src/main/java/com/team4/walletwatch/Main/Tab1Fragment.kt
  Development/app/src/main/java/com/team4/walletwatch/Main/Tab2Fragment.kt
  Development/app/src/main/java/com/team4/walletwatch/Settings/AboutFragment.kt
  Development/app/src/main/res/layout/fragment_about.xml
  Development/app/src/main/res/values/strings.xml
Labels: enhancement

#26 Completed [SPEN-8]
  Development/app/src/main/java/com/spendsages/walletwatch/DataManager.kt
  Development/app/src/main/java/com/spendsages/walletwatch/Main/Tab3Fragment.kt
  Development/app/src/main/java/com/spendsages/walletwatch/Settings/CategoryFragment.kt
  Development/app/src/main/res/values/strings.xml
Labels: enhancement

#27 Save Category Button [SPEN-37]
  Development/app/src/main/java/com/spendsages/walletwatch/Settings/CategoryFragment.kt
Labels: enhancement

#29 [SPEN-32] Delete Entries
  Development/app/src/main/java/com/spendsages/walletwatch/DataManager.kt
  Development/app/src/main/java/com/spendsages/walletwatch/Main/RecyclerAdapter.kt
  Development/app/src/main/java/com/spendsages/walletwatch/Main/Tab3Fragment.kt
Labels: documentation
